<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SwmarlyValheimQOL</AssemblyName>
    <RootNamespace>SwmarlyValheimQOL</RootNamespace>
    <Version>1.0.7</Version>
    <OutputPath>bin/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
</Project>
